---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: backend
  labels:
    app: demo-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
        version: v1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: api
          image: docker.io/library/demo-backend:v1
          imagePullPolicy: Never   # Built locally into k3s containerd via nerdctl
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: demo-db-credentials
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  namespace: backend
  labels:
    app: demo-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: demo-backend
