---
# Backend: Allow ingress from IngressGateway + frontend + Prometheus scraping,
#          egress to database + DNS + istiod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-demo-policy
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: demo-backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from Istio IngressGateway — used when VirtualService routes /api/*
    # directly to backend (bypassing frontend nginx proxy)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 8000
    # Allow from frontend pods — kept for defence-in-depth / future use
    - from:
        - namespaceSelector:
            matchLabels:
              name: frontend
          podSelector:
            matchLabels:
              app: demo-frontend
      ports:
        - protocol: TCP
          port: 8000
    # Allow Prometheus to scrape sidecar metrics — needed for Kiali mTLS visibility
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 15090
  egress:
    # Allow to PostgreSQL in data namespace only
    - to:
        - namespaceSelector:
            matchLabels:
              name: data
          podSelector:
            matchLabels:
              app: demo-postgres
      ports:
        - protocol: TCP
          port: 5432
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow Istio sidecar to reach istiod control plane (xDS + mTLS certs)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 15012
        - protocol: TCP
          port: 15010
---
# Database: Allow ingress from backend + Prometheus; egress to istiod
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: data-demo-policy
  namespace: data
spec:
  podSelector:
    matchLabels:
      app: demo-postgres
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: backend
          podSelector:
            matchLabels:
              app: demo-backend
      ports:
        - protocol: TCP
          port: 5432
    # Allow Prometheus to scrape sidecar metrics — needed for Kiali mTLS visibility
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 15090
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow Istio sidecar to reach istiod control plane (xDS + mTLS certs)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 15012
        - protocol: TCP
          port: 15010
