---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.51
    options:
      log-level: info
  ingress:
    enabled: false
  annotations:
    sidecar.istio.io/inject: "false"
  # Expose via LoadBalancer for direct access from internal network
  # NOTE: Jaeger operator doesn't support service annotations directly;
  # patch the service after deployment with:
  # kubectl patch svc jaeger-query -n observability -p '{"spec":{"type":"LoadBalancer"},"metadata":{"annotations":{"metallb.universe.tf/loadBalancerIPs":"172.20.20.25"}}}'
  # CHANGEME: replace 172.20.20.25 with a free IP from your MetalLB pool
